FROM resin/rpi-raspbian
COPY packages/lighttpd/ /opt/hm/
COPY packages-eQ-3/HS485D/ /opt/hm/
COPY packages-eQ-3/RFD/ /opt/hm/
COPY packages-eQ-3/WebUI/ /opt/hm/
COPY packages-eQ-3/LinuxBasis/ /opt/hm
COPY start_hm.sh /
#CMD ['start_hm.sh']

